import torch
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image
from model import get_art_classifier

# Ensure the exact same class order generated by your dataset loader
class_names = [
    'Academic_Art', 'Art_Nouveau', 'Baroque', 'Expressionism', 'Japanese_Art', 
    'Neoclassicism', 'Primitivism', 'Realism', 'Renaissance', 'Rococo', 
    'Romanticism', 'Symbolism', 'Western_Medieval'
]

def predict_image(image_path):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Loading model on {device.type.upper()}...")
    
    # 1. Load the model architecture and the saved brain weights
    model = get_art_classifier(num_classes=13)
    model.load_state_dict(torch.load("art_style_model.pth", map_location=device))
    model = model.to(device)
    model.eval() # Lock the model for testing
    
    # 2. Prepare the image (Resize and Normalize)
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    try:
        image = Image.open(image_path).convert('RGB')
    except Exception as e:
        print(f"Error loading image: {e}")
        return

    # Add a "batch" dimension because the model expects batches (even if it's just 1 image)
    input_tensor = transform(image).unsqueeze(0).to(device)
    
    # 3. Make the prediction
    with torch.no_grad():
        output = model(input_tensor)
        probabilities = F.softmax(output, dim=1) # Convert raw math to percentages
        top_prob, top_class = torch.max(probabilities, 1)
        
    predicted_style = class_names[top_class.item()]
    confidence = top_prob.item() * 100
    
    print("\n" + "="*30)
    print(f"Prediction: {predicted_style}")
    print(f"Confidence: {confidence:.2f}%")
    print("="*30 + "\n")

if __name__ == "__main__":
    # TODO: Put the file path of a test image here!
    sample_image = "test_image.jpg.webp" 
    
    predict_image(sample_image)